### ISSUE TITLE
Doesn't support multiple otherbuttontitles?

### ISSUE THREAD

**Issue by CokePokes** [nmaletm/STAlertView#1]
otherButtonTitles:(NSString *)otherButtonTitles is plural which is misleading since multiple buttons aren't implemented. 

" @param otherButtonTitles Text of the first button"

**Comment by nmaletm** [comment]
It's true, I tired to have the same interface as the native UIAlertView, but now I see that it's a bad idea. In the next release I'll fix it.

**Comment by nmaletm** [comment]
It has been fixed at version 1.0.0
